### ISSUE TITLE
Dropped iOS 7 support

### ISSUE THREAD

**Issue by asxasxasx** [ArtSabintsev/Harpy#103]
Any reason of dropping iOS 7 support? I have couple of project with old iOS support (they should work on old iPhones), but can't use Harpy for them anymore

**Comment by ArtSabintsev** [comment]
Yes, the iOS 9 SDK deprecates UIAlertView. 

iOS versions 1-7 make up less than 6% of all internet-connected iOS devices. It's not worth supporting.

**Comment by ArtSabintsev** [comment]
Closing for now, but feel free to respond here.
