### ISSUE TITLE
Not able to get Harpy to fire from appdelegate

### ISSUE THREAD

**Issue by ethanparker** [ArtSabintsev/Harpy#105]
I wasn't able to get it going from AppDelegate. So I just put all the code in my main view controller like this:

    [[Harpy sharedInstance] setAppID:@"xxxxxxxx"];
    [[Harpy sharedInstance] setPresentingViewController:self];
    [[Harpy sharedInstance] setAlertType:HarpyAlertTypeForce];
    [[Harpy sharedInstance] checkVersion];

Is that ok? Is there a reason this would break something?

**Comment by ArtSabintsev** [comment]
Sure, that's fine. Usually, you put it after the UWindow's makeKeyAndVisible line, but this is fine.
