### ISSUE TITLE
Harpy does not work on iOS 9

### ISSUE THREAD

**Issue by foffux** [ArtSabintsev/Harpy#106]
New versions of my apps have been released, but I do not see updating alert. It works on iOS 7. Do not why. Also on iOS 8 I have this issue.
Here you are my code:

```javascript
- (void)setupHarpy
{
    //Set the App ID for Foodendar app
    NSString* appId = [[NSBundle mainBundle] infoDictionary][@"AppStoreId"];
    //NSString* appId = @"355313284";
    [[Harpy sharedInstance] setAppID:appId];
    
    //Set the UIViewController that will present an instance of UIAlertController
    [[Harpy sharedInstance] setPresentingViewController:_window.rootViewController];
    //Set the tintColor for the alertController
    [[Harpy sharedInstance] setAlertControllerTintColor:kAlertControllerTintColor];
    //(Optional) Set the App Name for Foodendar app
    NSString* appName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleDisplayName"];
    [[Harpy sharedInstance] setAppName:appName];
    //Set the Alert Type for Foodendar app. By default, Harpy is configured to use HarpyAlertTypeOption
    [[Harpy sharedInstance] setPatchUpdateAlertType:HarpyAlertTypeForce];
    [[Harpy sharedInstance] setMinorUpdateAlertType:HarpyAlertTypeOption];
    [[Harpy sharedInstance] setMajorUpdateAlertType:HarpyAlertTypeForce];
    
    //Set Debug option as NO for release mode
    [[Harpy sharedInstance] setDebugEnabled:NO];
}
```

```javascript
- (void)applicationDidBecomeActive:(UIApplication *)application
{
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    
    [[Harpy sharedInstance] checkVersionDaily];
}
```

```javascript
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    //Setup Harpy
    [self setupHarpy];
    
    return YES;
}
```

**Comment by ArtSabintsev** [comment]
Hi - can you send me a sample project with all of the harpy stuff filled out that is also targeted for iOS 9?

Thanks!

**Comment by ArtSabintsev** [comment]
As I haven't gotten a response back via email or on here in a few days, I'm going to close this issue.

**Comment by foffux** [comment]
I replied to your request 
As you want, I will have to remove your pod and looking for something else 


Inviato da iPhone

**Comment by ArtSabintsev** [comment]
As I said before, please send me a sample project with your implementation and I will happily address the issue. As I didn't get a sample project, I can't diagnose the issue as it seems to work in the sample project that comes with this repo.

I'm still open to helping you.

**Comment by foffux** [comment]
I have already told you my implementation, from the very first mail. Have you got it? A sample project cannot be useful because or I will give you my actual project or a sample project is not the answer because it is not the same.
I have always used same configuration, but at the beginning it worked, iOS 7 I guess, but with iOS 9 or even with iOS 8 it did not work anymore. I thought you can see that also in other projects or even in your projects.

**Comment by ArtSabintsev** [comment]
If you could put your implementation in a small sample project and send not over to me, I'd appreciate I ate it. Harpy and Siten work in my projects.
