### ISSUE TITLE
AlertControllerTintColor will turn back to be Blue when button becomes highlight

### ISSUE THREAD

**Issue by hstdt** [ArtSabintsev/Harpy#110]
If I make button highlight,the button's tintcolor will turn back to blue.
AlertType is HarpyAlertTypeOption.

**Comment by hstdt** [comment]
![image](https://cloud.githubusercontent.com/assets/10215098/11988571/11a9af40-aa2d-11e5-8a97-ec06e780ef41.png)

**Comment by ArtSabintsev** [comment]
This is a known bug.

https://openradar.appspot.com/22209332

Nothing I can do about it.
