### ISSUE TITLE
the version supported suggest

### ISSUE THREAD

**Issue by yangchao0033** [ArtSabintsev/Harpy#114]
I look up your sourcecode. So I think you use the AlertViewController is the Cause about version supported iOS8+. So if I use HarpyAlertTypeNone type and handle delegate method by self，such as call your action method to link to AppStore ,can I solve to support iOS6 or iOS7 version?

**Comment by ArtSabintsev** [comment]
Yes, that should work just fine.

**Comment by yangchao0033** [comment]
it is decided on the company's product demand😂... my boss care...

**Comment by ArtSabintsev** [comment]
Send this to your bosses: https://developer.apple.com/support/app-store/
