### ISSUE TITLE
Custom Popup UI

### ISSUE THREAD

**Issue by robertodias180** [ArtSabintsev/Harpy#119]
is there any built in way to use a custom popup?

thanks

**Comment by ArtSabintsev** [comment]
Yes, use the `harpyDidDetectNewVersionWithoutAlert` delegate method.

**Comment by robertodias180** [comment]
The latest version of cocoa-pods does not contain that method yet. Can you please update it?

Also is there any built in way to set notify later in a custom UI?

thanks

**Comment by ArtSabintsev** [comment]
The latests version, 3.4.6, is on Cocoapods already.  Checkout the Sample project for an implementation of this method.

As for notifying later, you can schedule that yourself using the data you get from your custom UI.

**Comment by robertodias180** [comment]
Just one more think. Any special reason for this not to work in iOS7? 

Thanks

**Comment by ArtSabintsev** [comment]
Yes - I dropped UIAlertView support in favor or UIAlertController.
