### ISSUE TITLE
Call the delegate when the dialog is not shown

### ISSUE THREAD

**Issue by maurobender** [ArtSabintsev/Harpy#120]
It would be a good idea to have a method in the delegate to be called when the dialog is not shown because current version is equal or newer (in the case of a version being developed) than the version in the app store.

```objective_c
@protocol HarpyDelegate
...
- (void)harpyDidNotShowDialogBecauseCurrentVersionIsTheLatest;
...
@end
```

**Comment by getaaron** [comment]
Why?

**Comment by ArtSabintsev** [comment]
I don't think this is necessary at all. Closing the issue.

**Comment by maurobender** [comment]
Because you may want to wait until harpy has checked the app version to continue with the app's flow and act in consequence.

In my case if the user skips the update or the alert didn't even show up the app continues with the flow and redirects the user to the home screen, otherwise the app stays in the splash screen and wait until the user decides to choose the __update__ option and opens the AppStore, and if he returns to the app the update alert message is shown again.

The idea I came up to achieve this was to become harpy's delegate and hear when the user has taken an action. The issue here is that if the alert doesn't show up because the user has the latest app version the delegate is never notified of this and the app can't continue with the flow.

Maybe there is a better way to achieve this and I'm not seeing it.

**Comment by getaaron** [comment]
You can use HarpyAlertTypeForce to force an update. 

The approach you're discussing would block app launch every time there's not an update (or if there's even a connection issue), which would be a poor user experience.

**Comment by ArtSabintsev** [comment]
I'm with @getaaron. From a UX perspective, this is a bad idea. You never want to block the app from running. What I would do in your scenario is call Harpy's `checkVersion` method AFTER your root VC loads, instead of right away when the app launches.

**Comment by maurobender** [comment]
Yes, you're totally right.

In our case the client wants to not show anything if there is a forced update and this is determine now by harpy (via semantic versioning). How I've implemented now the launch process is only blocked when there's a forced update. Additionally in the object in charge of the launch process I'm listening to reachability changes to avoid calling harpy or continuing with the flow if there is any networking issues (letting the user know that the app is waiting for a working Internet connection)

Anyway I would suggest them the approach you've tell me and wait until the launch process is finished and the root or login VC are presented to call Harpy.

Thanks!

**Comment by ArtSabintsev** [comment]
Sounds good to me - good luck!
