### ISSUE TITLE
How to test before app store uploading in xcode?

### ISSUE THREAD

**Issue by samulegold2016** [ArtSabintsev/Harpy#121]
Dear Harpy Developers!!!

I had checked Harpy. it's very nice to check new version in appstore.
I had integrated Harpy in my xcode project. But I can't test update dialog in simulator.
I need to upload new version in appstore surely?
Is there any way to test before uploading in appstore?

I hope you will give me answer.
Thanks.

**Comment by ArtSabintsev** [comment]
Hi!

Just changed the version of your app in the Info.plist or in Xcode's project settings to something that's less than the current version that's in the App Store.

**Comment by samulegold2016** [comment]
App is not published in appstore yet. In this case, testing is not possible?
I had changed version 1.1. but I can't see dialog.

**Comment by ArtSabintsev** [comment]
Ah ok, just use the App ID from a different app. The Sample App loaded in harpy uses the AppID from iTunes Connect Mobile.
