### ISSUE TITLE
Users see update alert but app store doesn't have update yet

### ISSUE THREAD

**Issue by Pitsko** [ArtSabintsev/Harpy#123]
I have the next issue

Harpy shows alert about new version, but when user tap on button it goes inside App Store fro this app, but app doesn't have update, just open. After some time, update button in App Store appear (sometimes 30 minutes)

Any way to make update more smooth ?

**Comment by ArtSabintsev** [comment]
On some occasions, the JSON packet is updated by Apple _before_ the App propagates to all of Apple's CDNs.
