### ISSUE TITLE
'sharedApplication' and 'openURL:' is unavailable: not available on iOS (App Extension)

### ISSUE THREAD

**Issue by pouriaalmassi** [ArtSabintsev/Harpy#125]
## Description 

After cloning my project's repo and running `pod install` I'm getting the following build error regarding `sharedApplication `. 

```
/Path/To/Project/Pods/Harpy/Harpy/Harpy.m:328:21: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```

I'm seeing a similar build error regarding `openURL`

```
/Path/To/Project/Pods/Harpy/Harpy/Harpy.m:328:40: 'openURL:' is unavailable: not available on iOS (App Extension)
```

## Environment 

- Cocoapods: 0.39.0
- Xcode: 7.3 (7D175)

**Comment by ArtSabintsev** [comment]
You cannot access the AppDelegate or UIApplication from an App Extension. Remove the dependency on Harpy from the App Extension.
