### ISSUE TITLE
Deployment target check

### ISSUE THREAD

**Issue by attilat85** [ArtSabintsev/Harpy#126]
Don't show update dialog if the device iOS version is lower than the app supported iOS version.

Check pull request https://github.com/ArtSabintsev/Harpy/pull/124/commits/dc3e70b41901b91cad4c9c7b42569ba230ff36d7

**Comment by ArtSabintsev** [comment]
Thanks for the issue reminder.

I'm currently working out another issue in Harpy's sister repo. Once that's done, I'll get to this issue (which I'll also be adding to Siren).

**Comment by attilat85** [comment]
Alright!

**Comment by ArtSabintsev** [comment]
I added this feature to Siren, which is the Swift version of Harpy. I'll give you credit in the CONTRIBUTORS doc in that repo when I merge the PR. I'll be adding it to Harpy soon. 

For reference:
https://github.com/ArtSabintsev/Siren/pull/68/commits/5a50ae097f37ac586aa2b490c8c0b85e51400917

**Comment by ArtSabintsev** [comment]
Closing this issue in favor of #129.
