### ISSUE TITLE
forceLanguageLocalization doesn't change the language.

### ISSUE THREAD

**Issue by nmizoguchi** [ArtSabintsev/Harpy#127]
The alert shows english text even after setting to other SirenLanguageType (I'm using PortugueseBrazil).

**Comment by ArtSabintsev** [comment]
Are you using Siren or Harpy, or SirenLanguageType or HarpyLanguageType? This project is for Harpy.

**Comment by nmizoguchi** [comment]
Uh sorry, I thought I was in Siren's GitHub. My Bad.
