### ISSUE TITLE
Upgrade app whitout App Store

### ISSUE THREAD

**Issue by J-Arji** [ArtSabintsev/Harpy#128]
Can I use this to another server for Upgrade app (wihtout App Store)

**Comment by ArtSabintsev** [comment]
Unfortunately, no. This feature has been requested a few times, but everyone has different needs, and therefore, it's non-trivial to build a system that works for this case.

**Comment by J-Arji** [comment]
OK,Thanks :)

**Comment by ArtSabintsev** [comment]
You're welcome!
