### ISSUE TITLE
Harpy is crashing when app bundle id is not on the AppStore

### ISSUE THREAD

**Issue by martinprot** [ArtSabintsev/Harpy#135]
The below method is crashing because of an empty results array.
`results` exists, so it passes the `results != nil` condition, but the method access to its first value without checking the list count. `NSString *requiresOSVersion = results[0][@"minimumOsVersion"];`

```
- (BOOL)isUpdateCompatibleWithDeviceOS:(NSDictionary<NSString *, id> *)appData {
    NSArray<NSDictionary<NSString *, id> *> *results = appData[@"results"];

    if (results != nil) {
        NSString *requiresOSVersion = results[0][@"minimumOsVersion"];
        if (requiresOSVersion != nil) {
            NSString *systemVersion = [UIDevice currentDevice].systemVersion;
            if (
                ([systemVersion compare:requiresOSVersion options:NSNumericSearch] == NSOrderedDescending) ||
                ([systemVersion compare:requiresOSVersion options:NSNumericSearch] == NSOrderedSame)
               ) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    } else {
        return false;
    }
}

```

Solution : check `results.count` or access the first value with the method `[results firstObject]`

Thanks

**Comment by ArtSabintsev** [comment]
Will look into it this morning. Thank you

**Comment by ArtSabintsev** [comment]
Fixed and pushed to Cocoapods as v4.0.1.

**Comment by martinprot** [comment]
Thanks for your reactivity. I will test it as soon as possible.

**Comment by ArtSabintsev** [comment]
of course! This is one of my biggest libraries, so I try to have a quick turn around time whenever possible.
