### ISSUE TITLE
appID property is private

### ISSUE THREAD

**Issue by nikolay-petrov** [ArtSabintsev/Harpy#137]
Harpy 4.0.1: appID property is private. If appID property is not assigned then launchAppStore method is opening incorrect App Store page https://itunes.apple.com/app/id(null)

**Comment by ArtSabintsev** [comment]
Right, per the release notes, we no use the bundle identifier for app versioning. The App ID is extracted via the JSON results and kept as private for other purposes.

**Comment by ArtSabintsev** [comment]
Closing this issue, but feel free to ask any questions you have here.

**Comment by stephenwoodford** [comment]
I'm having issues with this as well. From what I can tell, I don't believe appID is ever being stored from the JSON results. Only 2 reference to appID are in the property declaration and a getter in the launchAppStore method ([self appID]).

**Comment by ArtSabintsev** [comment]
I'll take a look real quick.

**Comment by ArtSabintsev** [comment]
Oh, wow, my mistake! I must have forgotten to add the line of code that stores the appID after deciding that I would determine it dynamically.

This is one of the downside of maintaining two versions of the same library. Will fix this now

**Comment by ArtSabintsev** [comment]
Fixed and pushed in #138.

**Comment by ArtSabintsev** [comment]
If you use CocoaPods, please update to v4.0.2.

**Comment by stephenwoodford** [comment]
Seems to have fixed it for me. Thanks!

**Comment by ArtSabintsev** [comment]
Great - thanks for confirming!
