### ISSUE TITLE
UIAlertController tint color defaults to blue on highlight

### ISSUE THREAD

**Issue by nikolay-petrov** [ArtSabintsev/Harpy#139]
UIAlertController tint color defaults to blue on highlight.

Nice solution which works for me with other alert controllers is http://stackoverflow.com/a/33308392/2048218
Just add the tintColor after the presentViewController.

![simulator screen shot 21 2016 1 41 42](https://cloud.githubusercontent.com/assets/8525116/17005947/187ed60c-4ee6-11e6-8c03-d12f816c4f3a.jpg)
![simulator screen shot 21 2016 1 41 44](https://cloud.githubusercontent.com/assets/8525116/17005950/1ea7a112-4ee6-11e6-9bc4-72f288c20b2b.jpg)

**Comment by ArtSabintsev** [comment]
Accepted your PR and gave you credit.

The changes are in 4.0.3.
