### ISSUE TITLE
No visible @interface for 'Harpy' declares the selector 'setAppID:'

### ISSUE THREAD

**Issue by fabersky** [ArtSabintsev/Harpy#144]

**Comment by ArtSabintsev** [comment]
Yup. That variable is now private and unneeded. Harpy now works by fetching the bundleID.

**Comment by ArtSabintsev** [comment]
Feel free to comment if you have any more questions!

**Comment by fabersky** [comment]
ok @ArtSabintsev thanks for the quick response! so why not delete that variable from the code?

**Comment by ArtSabintsev** [comment]
I need it for something else internally. It's privately scoped now.
