### ISSUE TITLE
Changing Message Description and Button Text

### ISSUE THREAD

**Issue by ahanmal-carecloud** [ArtSabintsev/Harpy#147]
I would like to change the message text and button texts for the Update prompt. It seems that this used to be possible in the past (#5), but those properties are no longer exposed. Is there a new way using the current version of Harpy to change these strings, or is forking the repo the only way to do this. I only need it for English.

Thanks!

**Comment by ArtSabintsev** [comment]
@ahanmal-carecloud It's no longer possible, as I wanted to streamline the messages, which allowed for easy localization. 

In your position, I'd fork the repo and make the changes.
