### ISSUE TITLE
Not updating to latest version

### ISSUE THREAD

**Issue by himanthmaddi** [ArtSabintsev/Harpy#150]
My app has new version in AppStore two days back. But not getting alert from Harpy.

**Comment by ArtSabintsev** [comment]
Need more information. Show me how you integrated it into your app (code snippets).

**Comment by garudavn** [comment]
I have same issue :( !
Code integrated into my app:

`-(void)CheckNewVersion{
    // Set the UIViewController that will present an instance of UIAlertController
    [[Harpy sharedInstance] setPresentingViewController:_window.rootViewController];
    
    // (Optional) Set the Delegate to track what a user clicked on, or to use a custom UI to present your message.
    [[Harpy sharedInstance] setDelegate:self];
    
    // (Optional) The tintColor for the alertController
    //    [[Harpy sharedInstance] setAlertControllerTintColor:[UIColor purpleColor]];
    
    // (Optional) Set the App Name for your app
    //    [[Harpy sharedInstance] setAppName:@"iTunes Connect Mobile"];
    
    /* (Optional) Set the Alert Type for your app
     By default, Harpy is configured to use HarpyAlertTypeOption */
    [[Harpy sharedInstance] setAlertType:HarpyAlertTypeSkip];
    
    /* (Optional) If your application is not available in the U.S. App Store, you must specify the two-letter
     country code for the region in which your applicaiton is available. */
    //    [[Harpy sharedInstance] setCountryCode:@"en-US"];
    
    /* (Optional) Overrides system language to predefined language.
     Please use the HarpyLanguage constants defined in Harpy.h. */
    if ([[HFSetting GetCurrentLanguage] isEqualToString:@"Tiếng Việt"]) {
        [[Harpy sharedInstance] setForceLanguageLocalization:HarpyLanguageVietnamese];
    } else if ([[HFSetting GetCurrentLanguage] isEqualToString:@"English"]) {
        [[Harpy sharedInstance] setForceLanguageLocalization:HarpyLanguageEnglish];
    }
    // Turn on Debug statements
    //[[Harpy sharedInstance] setDebugEnabled:true];
    
    // Perform check for new version of your app
    [[Harpy sharedInstance] checkVersion];
}`

`- (void)applicationDidBecomeActive:(UIApplication *)application {
    [[Harpy sharedInstance] checkVersionDaily];
}`

`- (void)applicationWillEnterForeground:(UIApplication *)application {
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
    [[Harpy sharedInstance] checkVersion];
}`

**Comment by ArtSabintsev** [comment]
Your code blocks are a bit messed up in Github.

Did you use the Sample App for guidance?

https://github.com/ArtSabintsev/Harpy/blob/master/Sampe%20Project/Sample%20Project/AppDelegate.m

**Comment by garudavn** [comment]
Sure @ArtSabintsev. But it not working :(! 
Current my app available on appstore with version number 6.0. When i test Harpy, i have change version number down to 1.0 in xcode then worked, when i change from version 2.0 or heigher then not working.

**Comment by ArtSabintsev** [comment]
What is your app's bundle id?

**Comment by ArtSabintsev** [comment]
Is it available in the US app store?

Also. shoot me a link to your app.

**Comment by himanthmaddi** [comment]
For me issue solved after one day. Because information not updated in url but in AppStore. 
Thanks.

**Comment by ArtSabintsev** [comment]
Glad it's working for you, @himanthmaddi

**Comment by himanthmaddi** [comment]
Yup, worked like charm.

**Comment by ArtSabintsev** [comment]
Happy to hear that!
