### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Drag11** [ArtSabintsev/Harpy#152]
There is a crash in [Harpy bundleID] method. Only 1 user out of 5k is affected so far.
Crashlytics: http://crashes.to/s/671bd5cc406

**Comment by ArtSabintsev** [comment]
The `bundleID` method looks like this

```
- (NSString *)bundleID {
    return [NSBundle mainBundle].bundleIdentifier;
}
```

`bundleIdentifier` is a property Apple built into NSBundle within Foundation. This is one of those rare Apple-caused crashes.

The fact that it's 1/5000 means that it was a fluke, probably caused by the OS in some way.

Nothing I can do - sorry!
