### ISSUE TITLE
Harpy isn't working right now

### ISSUE THREAD

**Issue by tymorgan** [ArtSabintsev/Harpy#155]
Hey there, it looks like everything is good on our implementation. But for some reason it's not notifying users to update. Do you have any idea what might be happening?

**Comment by ArtSabintsev** [comment]
Need more info. Can you provide me with your App Store ID for the app? Also, is it in the US App Store?

**Comment by tymorgan** [comment]
Yes, it is in the US app store. This is our app ID: 923798849. We were stepping through the code and we saw that Harpy formats an app store url to get the version information and when we checked the url on the web browser on a phone and laptop it was the correct version. but when we added a breakpoint in the code and ran it, it showed the old version in the json blob.

**Comment by ArtSabintsev** [comment]
What version of Harpy are you using? The latest?

**Comment by ArtSabintsev** [comment]
I ask about the version because I fixed the bug that may be causing this issue a while back: https://github.com/ArtSabintsev/Harpy/blob/master/Harpy/Harpy.m#L151

**Comment by tymorgan** [comment]
We are not on the latest. I think that might be the issue. Thanks for your help.

**Comment by ArtSabintsev** [comment]
Thanks for following up. Good luck!
