### ISSUE TITLE
Remind even after update

### ISSUE THREAD

**Issue by yao23** [ArtSabintsev/Harpy#159]
A user complained it keeps asking her to download the newest version of the app even though when she clicked to update it already shows she has the latest version.

I set up Harpy as check new version every time open the app.

App Info
App: FashionStash
App Version: 2.1.30
URL: [iTunes url](https://itunes.apple.com/us/app/fashion-stash-style-inspiration/id1002815646?mt=8)
Harpy version: 4.0.11

Thanks in advance.

**Comment by ArtSabintsev** [comment]
Are you using the Force option?

**Comment by yao23** [comment]
No, I use Skip type.

`[[Harpy sharedInstance] setAlertType:HarpyAlertTypeSkip];`

**Comment by ArtSabintsev** [comment]
Can I see how you implemented the code?

**Comment by yao23** [comment]
// Set the UIViewController that will present an instance of UIAlertController
    [[Harpy sharedInstance] setPresentingViewController:self];

    /* (Optional) Set the Alert Type for your app
     By default, Harpy is configured to use HarpyAlertTypeOption */
    [[Harpy sharedInstance] setAlertType:HarpyAlertTypeSkip];

    // Perform check for new version of your app
    [[Harpy sharedInstance] checkVersion];

**Comment by getaaron** [comment]
This seems like another App Store propagation issue. A new version of this app was just released today.

**Comment by ArtSabintsev** [comment]
Alright, this has been happening to much. I think I may need to build in a delay by checking the `currentVersionReleaseDate` variable and adding 6 hours or so. What do you think @getaaron?

**Comment by yao23** [comment]
No, it's published at 4pm in App Store, but the user reported in the morning.

**Comment by getaaron** [comment]
It might need 24 hours. We could also try scraping the actual App Store page and see if we get the new version number on there.

**Comment by ArtSabintsev** [comment]
We could do that, ya. Need to think on it.

**Comment by ArtSabintsev** [comment]
Hey - just wanted to let you know that this issue has been fixed as of v2.0.0 of Siren: https://github.com/ArtSabintsev/Siren/releases/tag/2.0.0

Siren is the Swift-version of Harpy. It'll take me sometime to look into this issue in Harpy, since the codebase is a little bit behind that of Siren's.

**Comment by ArtSabintsev** [comment]
This is now fixed in Siren as of v4.1.0
