### ISSUE TITLE
Pod 4.1.0 not published yet?

### ISSUE THREAD

**Issue by skensell** [ArtSabintsev/Harpy#161]
I would like to use the feature you just released where it delays the presentation by one day, but it seems it's not available on Cocoapods.  Have you published it yet?

Thanks,

Scott

**Comment by ArtSabintsev** [comment]
Oh my bad - I thought it was published!

**Comment by ArtSabintsev** [comment]
@skensell Seems to work for me, and cocoapods.org says it's available. What issue are you seeing?

**Comment by skensell** [comment]
Oh whoops, yeah my bad.  I had to do the master repo update:
`ː ~/.cocoapods/repos/master [git:master:68c6b76] ː git pull`
