### ISSUE TITLE
appId works better than bundleId

### ISSUE THREAD

**Issue by wjiuxing** [ArtSabintsev/Harpy#163]
I manually released my App this morning but my old version app could not alert the Harpy alert view.
I used the Harpy v4.0.11 since it was released for several versions of my App.  I looked into this JSON responsed by the service https://itunes.apple.com/lookup?bundleId=xxx, this JSON gives me an previous version. Then I found the this JSON responsed by the service https://itunes.apple.com/lookup?id=xxx is updated to my latest version. This is the reason why my old version app could not show the Harpy alert. Unfortunately, the bundleId query is old until now I wrote this issue. 
So I think the appId query is faster than the bundleId. 
Would you please tell me why you made this URL query change from id to bundleId? Would you like to change it back?
Thanks very much.

**Comment by ArtSabintsev** [comment]
@wjiuxing 

I removed support for the `id` check a long time ago as people had a hard time finding it in the App Store. What I can do is re-add it, so that the end-user can choose between using the App ID or the BundleID.

Would that work for you?

**Comment by wjiuxing** [comment]
@ArtSabintsev 
Thanks. That can be a solution. 
Another found is that the result is correct if I append the country code to the itunes URL. 
The majority of my users are in China(including Taiwan), and some others from Canada, Australia and Japan. Doesn't it matter for the users in Canada, Australia and Japan, if I just use the country code cn? Maybe the countryCode is no longer optional?
Thanks again.

**Comment by ArtSabintsev** [comment]
countryCode is always going to be optional, but if it works for you, then go ahead and use it, since most of your users are in China. 

I'll make the change to harpy in the coming week.

**Comment by wjiuxing** [comment]
Wow... the json got updated finally. The update is delayed for about 24-hours... Thanks.

**Comment by ArtSabintsev** [comment]
yup - it is delayed for 24 hours. The app also delays it by 24 hours just in case.

**Comment by ArtSabintsev** [comment]
Alright, so I think  a better solution is to continue to use the bundleID, but to always append the US-App-Store, explicitly, by default. This happens implicitly right now (I think).

However, for people who explicitly choose another country, like yourself, then everything should work right away.

This is better then re-introducing the use of AppID.

**Comment by ArtSabintsev** [comment]
Decided against appending the US-App-Store by default as I could not glean any positive/negative effects from adding this feature.

Going to leave it as is, since it seems to work, and since no one else has risen this issue since in the last month.

Not going to fix what isn't really broken :)

Thanks anyway!

**Comment by wjiuxing** [comment]
Thank you very much. :)
