### ISSUE TITLE
Warning: Attempt to present <UIAlertController: > on <TopViewController: > whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by danartinho** [ArtSabintsev/Harpy#165]
Hi,
I set the presenting view controller to :    

    [[Harpy sharedInstance] setPresentingViewController:_window.rootViewController];

in `didFinishLaunchingWithOptions`.    
But, I got the warning that the `TopViewController` is not in the window hierarchy. Which is probably true, because in `TopViewController`, I was presenting other View Controller based on current login state.

    if (guestMode) {
       // etc etc
        [self presentViewController:nav1Controller animated:YES completion:nil];
    } else {
        // get current auth state
        authState = (int)[[NSUserDefaults standardUserDefaults] integerForKey:@"AuthState"];
        // check Login
        NSString *token = [SSKeychain passwordForService:@"Wolf" account:@"AccessToken"];
        //    NSLog(@"%@",token);
        if(token == nil) {
            // state is input code
            if (authState == C_AUTH_STATE_INPUT_CODE) {
                // etc etc
                [self presentViewController:nav2Controller animated:YES completion:nil];
            } else {
                // etc etc
                [self presentViewController:nav3Controller animated:YES completion:nil];
            }
        } else {
            if (authState == C_AUTH_STATE_INPUT_USERNAME) {
                // etc etc
                [self presentViewController:nav4Controller animated:YES completion:nil];
            } else {
                // etc etc
                [self presentViewController:nav5Controller animated:YES completion:nil];
            }
        }
    }

My guess is that the `TopViewController` has presented other ViewController before Harpy returned any check version result.     
I want to suggest you add a delegate method `harpyWillShowUpdateDialog` on the top of `- (void)showAlertController:(UIAlertController *)alertController`, so I can set the current `presentingViewController`.

Thanks,

**Comment by ArtSabintsev** [comment]
My advice to you is to wait until your view-hierarchy stabilizes _before_ performing the Harpy validation check. I can't really give more guidance than that on this specific problem.
