### ISSUE TITLE
    [[Harpy sharedInstance] setAppID:@""]; no longer available in new version

### ISSUE THREAD

**Issue by himanthmaddi** [ArtSabintsev/Harpy#166]
Throwing an error while using the above code. And there is no visible interface. 
How Harpy will check new version without app Id ?
And is that fine to use harpy exclude that line?

**Comment by getaaron** [comment]
Harpy currently uses the app's Bundle ID. The App ID has not been used in a while. The Bundle ID is unique in the App Store and it can be automatically detected. You may want to review the source code if you would like more clarification.

**Comment by ArtSabintsev** [comment]
Following up on what @getaaron said - Remove that one line of code, it;s from an older version of Harpy.

If you check the sample project, you'll see that this setup function is no longer needed.

https://github.com/ArtSabintsev/Harpy/blob/master/HarpyExample/HarpyExample/AppDelegate.m#L19

**Comment by himanthmaddi** [comment]
Thanks for explanation
