### ISSUE TITLE
How can testers check older versions of app if it is force update

### ISSUE THREAD

**Issue by himanthmaddi** [ArtSabintsev/Harpy#167]
I am showing **HarpyAlertTypeForce** to users when the new update available. Its all working great and thanks. 

But when our testers want to check the previous build, I have given them IPA file. So as I did its asking for update the app to latest version. 

How can I disable this for them? I know **github**  is the best option for this. But Is there any solution to overcome this?

**Comment by ArtSabintsev** [comment]
Sorry, I'm not sure if I fully understand.

You want your testers to test Harpy? There's no easy way (or even appropriate) way to do this using TestFlight or HockeyApp or Beta.

The best way to do this is to have them download Xcode and make the changes to the version in the Plist themselves. Then, run it locally on their simulator or device.

That would be my advice.

Closing this issue, but feel free to respond.

**Comment by himanthmaddi** [comment]
Thanks for response. 
My testers want to test my app which is using harpy. So harpy always asking to update to latest version.

**Comment by ArtSabintsev** [comment]
There's no way to do it outside of the scenarios I described. Best of luck!
