### ISSUE TITLE
"version" in the JSON from AppStore is now a string not an array

### ISSUE THREAD

**Issue by hughescr** [ArtSabintsev/Harpy#168]
Harpy seems to be looking for `results[0][@"version"]` to be an `NSArray *` but it's now just an `NSString`; Siren treats it as a string, but looks like Harpy doesn't.

**Comment by hughescr** [comment]
Never mind; I'm an idiot and misread the code.

**Comment by ArtSabintsev** [comment]
No problem - glad you figured it out!
