### ISSUE TITLE
[setCountryCode:] multiple countries? 

### ISSUE THREAD

**Issue by JoeriBultheel** [ArtSabintsev/Harpy#173]
Hello,

What if my app is available in a small list of countries only?
Is it possible to insert an array or to seperate country codes in the string by a comma? 
Looking at the implementation of Harpy I think this is not possible... 

I hope I'm wrong. 

Thnx!

**Comment by ArtSabintsev** [comment]
You only need to insert one  to get the App Store version check to work. Pick one country your app is available him, and you should be fine. It defaults to the US App Store.

**Comment by JoeriBultheel** [comment]
Ok, thank you!
