### ISSUE TITLE
App Store Rejected

### ISSUE THREAD

**Issue by orinmurphy** [ArtSabintsev/Harpy#174]
I received this message from App Review:

> Guideline 4.0 - Design
> 
> Your app includes an update button or alerts the user to update the app. To avoid user confusion, app version updates must utilize the iOS built-in update mechanism.

**Comment by ArtSabintsev** [comment]
That's a first! Did the message pop up during the test? They have no way of knowing Harpy is in there unless this happens. I don't they have a static analysis check against Harpy methods.

Can I see your implementation of Harpy?

**Comment by orinmurphy** [comment]
Actually, it's strange... I got more information and they sent a screenshot of a section of my app where a cell displays the version number of the app. The cell does nothing when it is tapped, it is just for display purposes, but user interaction is enabled, which i have since disabled. 

My implementation of harpy is standard: 
```
    [[Harpy sharedInstance] setPresentingViewController:self.window.rootViewController];
    [[Harpy sharedInstance] setAlertControllerTintColor:kMainGreenColor];
    [[Harpy sharedInstance] setAppName:kAppName];
    [[Harpy sharedInstance] setCountryCode:@"CA"];
    [[Harpy sharedInstance] checkVersion];
```

I will post here again if it is rejected again.

**Comment by ArtSabintsev** [comment]
Hmm, that is interesting. Might just be a bad reviewer. I've had that happen every so often. Definitely resubmit again, and keep me posted.

**Comment by ArtSabintsev** [comment]
By this, I'm referring to a reviewer going a bit too far :)

**Comment by ArtSabintsev** [comment]
Any update?

**Comment by orinmurphy** [comment]
Yes! Just got an email that the resubmit was approved. All good!

thanks

**Comment by ArtSabintsev** [comment]
Great - thanks for the update!
