### ISSUE TITLE
Not getting alert for update for iOS 7

### ISSUE THREAD

**Issue by aniketmuruskar** [ArtSabintsev/Harpy#175]
======
Beginner to iOS app development. Using **Harpy (3.4.7)** in my project. Having following configuration for app
> Deployment target: iOS 7,  using Xcode 7.3

Having following code in my AppDelegate.m :
> [[Harpy sharedInstance] setAppID: #appid];
> [[Harpy sharedInstance] setPresentingViewController:#view controller];
> [[Harpy sharedInstance] setDelegate:self];
> [[Harpy sharedInstance] setAppName:#app name];
> [[Harpy sharedInstance] setCountryCode:#country code];      
> [[Harpy sharedInstance] checkVersionDaily];

Getting this warning.
> **Please make sure that you have set _appID and _presentationViewController before calling checkVersion, checkVersionDaily, or checkVersionWeekly**

If i switch to iOS 8.1 as iOS deployment target, will it works ?

As a learner, please tell me what values need to change in Xcode configuration for testing purpose (in **General** tab) i.e **Version** or **Build** input values

Thanks in Advance

**Comment by ArtSabintsev** [comment]
Please upgrade to v4.1.5 of Harpy. You won't need the AppID at that point.

**Comment by ArtSabintsev** [comment]
Closing due to lack of follow-up. Feel free to re-open.
