### ISSUE TITLE
Missing _appID ?

### ISSUE THREAD

**Issue by JoeriBultheel** [ArtSabintsev/Harpy#176]
I followed all instructions to implement Harpy, and now the new version of my app is in the appStore, there is no prompt appearing in my older app. I checked a bit the flow, and It appears the _appID var is missing in the checkversion method. I don't get it, how is it supposed to be there? You mention it nowhere in the installation instructions. What is this var supposed to represent? Is it the bundle identifier? The version number? I thought it might be fetched by another method as there is no need to set it manually, but then again I don't see it implemented. 

Please help! Thnx.

**Comment by JoeriBultheel** [comment]
Ok I googled my own appstore app link and copied the appID from there and set it in the didFinishLaunching method. I highly advice you to put the "set the appID"-step in the install instructions, as it is crucial for Harpy to work, and not let people find out Harpy doesn't work when they followed all instructions and then get a surprise when their new app is live. 

(still really love this project though)

**Comment by ArtSabintsev** [comment]
Hey thanks for the message. I swear I made it such that all you need is the bundleID. Also, there's a 24 hour delay in presenting the notifications if you use the just the bundleID method. I'll need to test this later.

**Comment by ArtSabintsev** [comment]
Ok, couple things.

- The code makes use of the bundleID: https://github.com/ArtSabintsev/Harpy/blob/master/Harpy/Harpy.m#L229-L245

- What version of Harpy did you ship with?

**Comment by JoeriBultheel** [comment]
I just used cocoapods => pod 'Harpy'. My Podfile.lock says it's on 3.3.10.

**Comment by JoeriBultheel** [comment]
Must've been an inconsistent version then... I've looked it up in my git history and i've cocoapod-added the pod on 9th july 2017.

**Comment by ArtSabintsev** [comment]
Current version is 4.1.5. Have you done a `pod update` in the last few months to a year?

**Comment by ArtSabintsev** [comment]
Also, in case your project is in Swift, there's a version of the library in Swift as well: http://github.com/artsabintsev/siren

**Comment by JoeriBultheel** [comment]
Tried manually setting the version to 4.1.5 in the podfile and came across this issue:
- `Harpy (= 4.1.5)` required by `Podfile`

Specs satisfying the `Harpy (= 4.1.5)` dependency were found, but they required a higher minimum deployment target.

I guess it was updating till the latest possible pod-version for my xcode project setting. I currently have to support iOS 8 still, so I will do it the old way with the _appID. You can remove this issue, as it is not really relevant.

Thnx!

**Comment by ArtSabintsev** [comment]
That's so weird. Harpy supports iOS 8: https://github.com/ArtSabintsev/Harpy/blob/master/Harpy.podspec#L6

Alright, but you should really drop iOS 8 if you can (https://developer.apple.com/support/app-store/). iOS 1-8 are less than 3% of the global marketshare. I'm assuming you have other reasons for supporting it, but just throwing my 2 cents out anyway!

**Comment by JoeriBultheel** [comment]
I found the issue. My podfile had this line:
platform :ios, '7.1'

I took over the project, and I was looking at the xcode-project deployment target, which was 8.0. So sorry, entirely my fault! Thnx again :)

**Comment by ArtSabintsev** [comment]
Glad you figured it out!

No problem, my friend! Happy to help!

Thanks for using Harpy!

**Comment by JoeriBultheel** [comment]
heehee thank you for making it my friend! 
it's awesome. 
Bye
