### ISSUE TITLE
Provide option to show force alert only if the user is on a version that older than a manually set version.

### ISSUE THREAD

**Issue by stevemoser** [ArtSabintsev/Harpy#178]
I would like to use Harpy to check the semantic app version number against a manually set version number and show the force alert if it is older than that manually set version number otherwise show the normal alert.

**Comment by ArtSabintsev** [comment]
Hey,

To do this, you'll need to get this working using an external configuration file that is fetched from the server and toggles siren on/off for specific versions. That's how many others get to this level of granularity from a dynamic standpoint.

Closing the issue, but will follow up if you follow up.

**Comment by stevemoser** [comment]
Okay. At least exposing the semantic version check functionally should be enough to get to going since the comparison may rely on a version not in the store.

**Comment by ArtSabintsev** [comment]
Sure, could your stub out the code in a PR, and I can take it from there? I'd like to see how you're thinking about this problem.

Also, in case  you're using Swift, there's a Swift version available: https://github.com/artsabintsev/siren

**Comment by stevemoser** [comment]
So it looks like the version checker is a one liner so exposing it maybe isn't a priority. I was thinking Harpy strictly followed semantic versioning and allowed 'alpha' and 'beta' in the version string and such like [Sparkle's implementation](https://github.com/sparkle-project/Sparkle/blob/3a5c620b60f483b71f8c28573ac29bf85fda6193/Sparkle/SUStandardVersionComparator.m). You might want to update the README so it is clear that only numbers are supported.

**Comment by ArtSabintsev** [comment]
It's in there already: https://github.com/artsabintsev/siren#about

Says numbers explicitly.

```
Semantic Versioning is a three number versioning system (e.g., 1.0.0)
Harpy also supports two-number versioning (e.g., 1.0)
Harpy also supports four-number versioning (e.g., 1.0.0.0)
```

**Comment by stevemoser** [comment]
The wording

> Semantic Versioning is a three number versioning system

makes it sound like that is a requirement of the linked to Semantic Versioning spec instead of a limitation of Harpy/Siren matching the Semantic Versioning spec. Maybe update it to say that the lib currently only supports a numbers only sub-spec of Semantic Versioning.

**Comment by ArtSabintsev** [comment]
ok, will do! Thanks!

**Comment by stevemoser** [comment]
Thank you for providing awesome libraries!

**Comment by ArtSabintsev** [comment]
My pleasure! Thanks for the suggestions - appreciate it!
