### ISSUE TITLE
Harpy Displaying Behind Touch ID View

### ISSUE THREAD

**Issue by hawkeye1194** [ArtSabintsev/Harpy#182]
My app utilizes Touch ID for login purposes and the issue that I am having is that there is not a delegate method for Harpy that allows me to determine when Harpy is done attempting to check for app updates (success or failure). I need to present Touch ID after checking for an app update so that Touch ID does not cover the Harpy update alert if there actually is an app update. As of now I am just invaliding the LAContext for Touch ID if harpyDidShowUpdateDialog is called but that is not a very clean looking solution to see Touch ID disappear after being presented. If I am missing something please let me know on how I can resolve this. Thanks.

**Comment by ArtSabintsev** [comment]
Why not do TouchID first, and then display initiate the check by Harpy, instead of the other way around?

**Comment by hawkeye1194** [comment]
I do think it would be useful for checkVersion to have a callback block when it has completed checking for updates such as -(void)checkVersion:(void (^)(void))completion; 

I only want to present Touch ID if there is no app update. I don't want both presenting as it would confuse the users.

**Comment by hawkeye1194** [comment]
If I did that I would have to call checkVersion in the LAContext's reply callback function so even then there would be a delay in the Harpy dialog presentation and it's possible they could login before the Harpy dialog is presented which I would not want.

**Comment by ArtSabintsev** [comment]
What's wrong with them logging in before presenting Harpy? Nothing says the version check needs to happen on launch. I don't always do it on launch myself.

**Comment by hawkeye1194** [comment]
I want to force users to use the latest version of the iOS app as my app is a lot more critical than something like Facebook.

**Comment by ArtSabintsev** [comment]
So your idealized solution is a block-based API vs the asynchronous one that we have now, correct?  I need to think on this, since you're using Harpy in a different way than I had it intended, especially with the dependencies you have on login/touch-id. 

You have no flexibility here? 

If I may prod a bit more - what's wrong with having a user login before updating your app? Are you afraid of a crash of some sort, or stale data?

**Comment by hawkeye1194** [comment]
Asynchronous still but additional overloads that have blocks for the case of the login/touch-id issue. We want to be in control so that we do not have to worry about issues that arise when dealing with multiple web service API versions and multiple iOS app versions as each customer has their own set of web services. If we roll out breaking changes we don't want to have to deal with old API support.

**Comment by ArtSabintsev** [comment]
Alright, good enough. I'll add an overloaded version of the checkVersion method that calls out to a completion block on success and failure. I'll need a couple days to implement it (probably no later than Wednesday) as I have a few other things going on. Sound good?

**Comment by hawkeye1194** [comment]
If you think that is the best solution as well then that sounds good to me. Unless you can think of something even better. Really appreciate it, thanks. And no rush whatsoever.

**Comment by hawkeye1194** [comment]
Either that or just another delegate method to the harpy delegate that is already there might be better? All I really need is to check if there is an update and if there is no update present Touch ID.

**Comment by ArtSabintsev** [comment]
So I thought about it over the last couple hours. The block-based API isn't ideal, but the existing delegate method is: `harpyDidDetectNewVersionWithoutAlert`.

When that method gets entered, simply:

```
- Set the Harpy delegate = nil
- Do a checkVersion
- On didBecomeActive, re-initialize the delegate.
```

**Comment by ArtSabintsev** [comment]
Closing the issue, but feel free to respond. I'll follow up as needed.
