### ISSUE TITLE
Dutch translation error

### ISSUE THREAD

**Issue by wbison** [ArtSabintsev/Harpy#184]
"Update Beschikbaar" should be "Update beschikbaar"

**Comment by ArtSabintsev** [comment]
Why not capitalized? It's capitalized in English, meaning, I made the conscious decision to have all the button text be capitalized.

**Comment by wbison** [comment]
Only the first word of a sentence should be capitalized in Dutch (with a lot of exceptions but not here).

You want proof? Here is proof! Apple mail app, unsubscribe from mailinglist - both in the alert title and the button label:

![image](https://user-images.githubusercontent.com/309892/33090762-6f537fc4-cef5-11e7-923b-b1da56e3bd10.png)

Sorry to come up with a silly issue like this but it really is incorrect and looks bad..

**Comment by ArtSabintsev** [comment]
Alright - thanks for the proof. Please open a PR with the change made to the source file and tests and I'll merge it in.
