### ISSUE TITLE
App Store URL returns an older JSON Result even tho there is a new app update

### ISSUE THREAD

**Issue by veanovenario** [ArtSabintsev/Harpy#186]
Our app got approved in the App Store more than 24 hrs ago, but when I opened an old app, Harpy didn't show an alert. When I debugged and checked the logs, it seems that I am getting an old JSON Result from the app store URL lookup (https://itunes.apple.com/lookup?bundleId=XXXX) which means the app thinks that the installed version is updated. I get this log:
"[Harpy]: Currently installed version is newer."

However:
- The app store version is 1.2.0 now
- When I run the app with Harpy v4.1.9, I get version = 1.1.0
- When I go to the app store URL on a desktop browser, I get version 1.2.0

Would you know why this happens? Should we disable caching somewhere in the app? Thanks!

**Comment by ArtSabintsev** [comment]
Hi!

Could you please provide me with your Bundle ID? 

Thanks!

**Comment by veanovenario** [comment]
com.baxtersart.bam

**Comment by ArtSabintsev** [comment]
I see the following when putting your Bundle ID in the sample project:

```
            currentVersionReleaseDate = "2017-11-27T18:18:45Z";
            minimumOsVersion = "8.0";
            version = "1.2.0";
```

**Comment by ArtSabintsev** [comment]
<img width="2672" alt="screen shot 2017-11-28 at 9 34 57 pm" src="https://user-images.githubusercontent.com/854860/33355096-026bdf66-d484-11e7-8544-43aff76ec4d5.png">
 
Here's a screenshot.

**Comment by ArtSabintsev** [comment]
Can I see how you configured Harpy in your codebase? Rather, could you drop the snippets of code related to harpy and where you placed them.

**Comment by veanovenario** [comment]
Hmm, seems okay on your side. This is the response on my side:

**Comment by veanovenario** [comment]
Hmm, seems okay on your side. This is the response on my side:
![screen shot 2017-11-29 at 10 42 06 am](https://user-images.githubusercontent.com/8588177/33355355-22381c60-d4f2-11e7-8224-83b052fcde79.png)

Codes were added here:
![screen shot 2017-11-29 at 10 40 57 am](https://user-images.githubusercontent.com/8588177/33355369-355f6ab4-d4f2-11e7-86a6-017f5126c887.png)

**Comment by ArtSabintsev** [comment]
I wonder if you're hitting a different CDN than I am. If you don't mind me asking, where in the world are you located?

**Comment by veanovenario** [comment]
Harpy worked before when we were testing it. Just that now, the alert wouldn't show because of the outdated JSON response.

**Comment by veanovenario** [comment]
Singapore :D

**Comment by ArtSabintsev** [comment]
<img width="2672" alt="screen shot 2017-11-28 at 9 56 16 pm" src="https://user-images.githubusercontent.com/854860/33355809-0ef713c4-d487-11e7-9e15-ebfe9cd78959.png">

Your App Store is available everywhere, correct? Therefore, it doesn't matter which App Store I check against. By default, Harpy checks against the US one. So I changed the Country Code to Singapore, and I still get 1.2.0. So that means it's not an App Store issue. I think it may be a CDN issue.

I see you set the `delegate` - are you capturing any analytics in the `harpyDidShowUpdateDialog` delegate method that you can look up online?

**Comment by veanovenario** [comment]
I'm not familiar with CDN, but I tried the URL on the Safari browser in the same phone as the installed app. It displayed the correct version too (1.2.0). I'll try to debug some more.

I wasn't the one who added Harpy in the codes, but it doesn't seem to have `harpyDidShowUpdateDialog` method when I looked for it.

**Comment by ArtSabintsev** [comment]
Ah, understood. No problem - thanks for the update. 

As for it being a caching issue, the request is initialized with `NSURLRequestReloadIgnoringCacheData`, so it's not an issue:

```
- (void)performVersionCheck {
    NSURL *storeURL = [self itunesURL];
    NSURLRequest *request = [NSMutableURLRequest requestWithURL:storeURL cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:30.0];

    [self printDebugMessage:[NSString stringWithFormat:@"storeURL: %@", storeURL]];

    NSURLSession *session = [NSURLSession sharedSession];
    NSURLSessionDataTask *task = [session dataTaskWithRequest:request
                                            completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
                                                if ([data length] > 0 && !error) { // Success
                                                    [self parseResults:data];
                                                }
                                            }];
    [task resume];
}
```

I'm going to close the issue, as I think most of users will probably see the alert. Feel free to respond or reopen the issue if you have any more information or questions.

Good luck!

**Comment by veanovenario** [comment]
Wish I knew more about how CDN works. But yea, maybe that is the issue.

It seems that when I use our wifi, I get outdated JSON response in the app only.
If I use my own 4G data, I get the updated one. 😅

Thanks for your time! :)

**Comment by ArtSabintsev** [comment]
No problem! Here's more info on CDNs: https://en.wikipedia.org/wiki/Content_delivery_network

**Comment by dongmai** [comment]
I got the same issue, how can we resolve it? :(

**Comment by ArtSabintsev** [comment]
Please read through the solution posted here, or open a new issue and we can have the conversation there.
