### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by differenz-system** [ArtSabintsev/Harpy#190]
Today one of our live app stop working, it is asking for update every time user start the app. seem like issue with Harpy server. please check

**Comment by getaaron** [comment]
There is no Harpy server. See `itunesURL` method which builds the URL that is checked. You can hit the URL in the browser and inspect the result.

What is the generated iTunes URL for the app? Sometimes Apple updates this URL when you publish a new version before distributing the version.

**Comment by differenz-system** [comment]
This is URL https://itunes.apple.com/lookup?bundleId=com.caregiver.caregivelite and version is 5.6 still it is showing as pop-up

**Comment by ArtSabintsev** [comment]
@differenz-system 

We need a lot more information.

- What version of Harpy does your app use?
- What was the previous version of your app?
- What's the current verison of your app?
- What alert-type setting did you use? Force? Optional? Skip?
- How often does the alert pop up? (immediately, daily, weekly)

Any sample code you can provide would be helpful.

**Comment by jigneshk** [comment]
@ArtSabintsev,

Please see my comment below.

What version of Harpy does your app use?
-	4.1.9
What was the previous version of your app?
-	5.6
What's the current version of your app?
-	5.7
What alert-type setting did you use? Force? Optional? Skip?
-	Force
How often does the alert pop up? (immediately, daily, weekly)
-	immediately

Thanks
Jignesh

**Comment by ArtSabintsev** [comment]
Hey @jigneshk - sorry for taking so long to respond. Please open up a new ticket if this is a still a problem, and I'll get back to you soon.
