### ISSUE TITLE
setForceLanguageLocalization does not work for me

### ISSUE THREAD

**Issue by balkarov** [ArtSabintsev/Harpy#195]
Hello!
Thank you for your library!

I use last version 4.1.12
Install via cocoapods

My code:
```
[[Harpy sharedInstance] setAlertType:HarpyAlertTypeForce];
[[Harpy sharedInstance] setPresentingViewController:[self topViewController]];
[[Harpy sharedInstance] setForceLanguageLocalization:HarpyLanguageArabic];
[[Harpy sharedInstance] checkVersion];
```

But alert always show message in English.
I try any Localization, but always the same.

**Comment by ArtSabintsev** [comment]
Looks like you may have found a bug - will look at it in the next couple days.

**Comment by ArtSabintsev** [comment]
Hmm, I cannot reproduce this issue. I tried in the sample project and it worked without any issues. See the screenshots below for Arabic and Russian.

<img width="598" alt="screen shot 2018-05-15 at 7 47 05 pm" src="https://user-images.githubusercontent.com/854860/40089274-e2286ab6-5878-11e8-906d-9753c7823dde.png">

<img width="598" alt="screen shot 2018-05-15 at 7 48 00 pm" src="https://user-images.githubusercontent.com/854860/40089275-e233b808-5878-11e8-9781-f9ff541c90db.png">

**Comment by balkarov** [comment]
Look this
![2018-05-16 7 10 09](https://user-images.githubusercontent.com/6030335/40096160-48a936da-58d8-11e8-8f91-32bf52730524.png)

**Comment by balkarov** [comment]
![asset](https://user-images.githubusercontent.com/6030335/40096226-9c8f42d0-58d8-11e8-9645-3b4fb573bf22.JPG)

**Comment by balkarov** [comment]
```
[[Harpy sharedInstance] setAlertType:HarpyAlertTypeForce];
    [[Harpy sharedInstance] setAppName:@"Sample"];
    [[Harpy sharedInstance] setForceLanguageLocalization:HarpyLanguageRussian];
    [[Harpy sharedInstance] setPresentingViewController:[self topViewController]];
    [[Harpy sharedInstance] checkVersion];
```

**Comment by balkarov** [comment]
I run on real device, not on the simulator.

**Comment by balkarov** [comment]
In your example you tried not via cocopods and you run on the simulator.
Could you reproduce it install library via cocoapods and run on real device?

**Comment by ArtSabintsev** [comment]
Will look again in the evening.

**Comment by ArtSabintsev** [comment]
Alright, I've confirmed that there is indeed a bug when installing via Cocoapods. Looking into it now.

**Comment by ArtSabintsev** [comment]
ok, I take that back, what I saw was not a bug, but me not setting up Harpy properly. I re-ran my tests by installing harpy via CocoaPods on an app I'm currently working on. I tried multiple times with multiple languages and on cold and warm launch, and it worked every single time.

I'm not sure how else to help you unless you can provide me with a sample project.

**Comment by balkarov** [comment]
Thank for your checking. 
Ok, I’ll prepare project and will send you

**Comment by ArtSabintsev** [comment]
Great thanks!

**Comment by balkarov** [comment]
@ArtSabintsev I found problem in my project. 
I replaced  `localizedStringForKey` with my custom method in `runtime.h`
And app use always main Localizable file. I changed something in my code and all works now.
Thank you very much for you library!
Have a good time!
