### ISSUE TITLE
App Store latest build version detected new version

### ISSUE THREAD

**Issue by viktoricalonia** [ArtSabintsev/Harpy#198]
Good day, 

App Store latest version build is detecting a new version build even it is in new version. (bug)

When i try to install this same build version from TestFlight, it is not detecting new version (expectation)

```
- (void)setup {
Harpy *harpy = Harpy.sharedInstance;
harpy.delegate = self;

  CTCarrier *carrier = [[CTTelephonyNetworkInfo new] subscriberCellularProvider];
  NSString *countryCode = carrier.isoCountryCode;
  harpy.countryCode = countryCode;

  harpy.alertType = HarpyAlertTypeNone;
  harpy.majorUpdateAlertType = HarpyAlertTypeNone;
  harpy.minorUpdateAlertType = HarpyAlertTypeNone;
  harpy.patchUpdateAlertType = HarpyAlertTypeNone;
  harpy.revisionUpdateAlertType = HarpyAlertTypeNone;

  [harpy checkVersion]
}

- harpyDidDetectNewVersionWithoutAlert:(NSString *)message {
// block user if current build is outdated
// show custom view if outdated.
}
```

P.S. I hope i can get an immediate reply since it is crucial on our app's UX. We don't let user use our app with outdated builds.

**Comment by ArtSabintsev** [comment]
Hi,

Can you please provide me with your bundle ID? I need to verify this bug on my end.

**Comment by jassimkm** [comment]
com.meridian.wildlyyours

**Comment by ArtSabintsev** [comment]
So for that bundleID, I see that v1.2 app was released on `2018-06-11T14:29:22Z`. Since `setShowAlertAfterCurrentVersionHasBeenReleasedForDays` defaults 1, a prompt will not appear for 24 hours after launch, which is in about 9.5 hours.

**Comment by prgorasiya** [comment]
I also have a question related to this, how can I modify time interval `setShowAlertAfterCurrentVersionHasBeenReleasedForDays` to let's say 3 hours?

**Comment by ArtSabintsev** [comment]
you can't, without forking the code and making a change to how this value works. 

It's an `Int` that represents days.

This is purposefully done to get around an issue where the JSON updates faster than the the binary becomes available to uses.

**Comment by ArtSabintsev** [comment]
Closing this issue, but feel free to continue commenting and I'll follow up.

**Comment by ArtSabintsev** [comment]
No problem! Good luck!
