### ISSUE TITLE
itunes lookup api old response 

### ISSUE THREAD

**Issue by ultimatevegance** [ArtSabintsev/Harpy#203]
The performVersionCheck method returns older version of itunes data, but when I try to change the request method into "POST",it always return the newest data ;
```objc
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:storeURL cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:30.0];
    [request setHTTPMethod:@"POST"];

```

**Comment by ArtSabintsev** [comment]
I think it might be a caaching issue, as https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/ doesn’t say anything about POST.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ultimatevegance** [comment]
@ArtSabintsev  thanks for your response ,maybe it is the caching issue, and may be I should wait for 24hrs to see the problem still exists .

**Comment by ArtSabintsev** [comment]
Yes, please wait at least 24 hours, per the directions in the README. Closing this issue. Feel free to comment if the issue persists

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
