### ISSUE TITLE
Port codebase to Swift

### ISSUE THREAD

**Issue by ArtSabintsev** [ArtSabintsev/Harpy#51]
I'll still retain the Objective-C codebase for as long as it's deemed necessary. Just need to do some real-world Swift coding now.

Onwards and Upwards!

**Comment by getaaron** [comment]
Interested on pairing on this now? Swift 1.1 seems relatively stable…

**Comment by ArtSabintsev** [comment]
Yes, relatively soon actually. Its one of the projects I'm tackling this week. Should be a pretty easy port. I'll ping you when I have some sample up and running.

**Comment by ArtSabintsev** [comment]
@getaaron and I have released a Swift port of Harpy. We've called it Siren, and it can be found here: http://github.com/ArtSabintsev/Siren
