### ISSUE TITLE
side effect crash caused by cocoaPod issues with multiple targets

### ISSUE THREAD

**Issue by frranck** [ArtSabintsev/Harpy#68]
It is basically a CocoaPod issue, but it can make the library crash when seeing an update:

I have a project with many targets: I don't understand why, but cocoapod can't access ressources in different targets than the first one. (this can be fixed by making a reference of the Harpy.bundle in the project bundle).

This causes a crash in:         

_theNewVersionMessage = [NSString stringWithFormat:HARPY_LOCALIZED_STRING(@"A new version of %@ is available. Please update to version %@ now."), _appName, currentAppStoreVersion];

because it calls [NSString stringWithFormat:nil 

We can prevent the crash by changing this macro:

#define HARPY_LOCALIZED_STRING(stringKey) ([[NSBundle mainBundle] pathForResource:@"Harpy" ofType:@"bundle"] ? [[NSBundle bundleWithPath:HARPY_BUNDLE_PATH] localizedStringForKey:stringKey value:stringKey table:@"HarpyLocalizable"] : stringKey)

It will break the localisation, but not the app...

**Comment by ArtSabintsev** [comment]
Does localization break with your solution?

**Comment by ArtSabintsev** [comment]
Also, I was thinking of changing these macros to be read-only properties, like I did in [Siren](http://githu.com/ArtSabintsev/Siren), so I may just look at your solution and make the change simultaneously.

**Comment by frranck** [comment]
Yes it does break (messages will be in english) because it can't find the bundle...

**Comment by ArtSabintsev** [comment]
Ah, well if localization breaks with your solution, than the solution won't be accepted. You might want to post this issue over at CocoaPods' github repo.

**Comment by frranck** [comment]
My solution doesn't break the localization, it prevents the app from crashing when there is an issue accessing the bundle.

**Comment by ArtSabintsev** [comment]
Ah - ok, I understand now. I'll definitely add it in this evening.

**Comment by ArtSabintsev** [comment]
I'll close this issue, but keep the PR open until I vet it. 

Thank you!
