### ISSUE TITLE
Use of HarpyAlertTypeSkip always skips prompt after first check

### ISSUE THREAD

**Issue by nathanhosselton** [ArtSabintsev/Harpy#71]
In the setup for `HarpyAlertTypeSkip`, the object for `HarpyDefaultSkippedVersion` is being set to `currentAppStoreVersion` on lines 306-307 of Harpy.m
```objc
// Store currentAppStoreVersion in case user pushes skip
[[NSUserDefaults standardUserDefaults] setObject:currentAppStoreVersion forKey:HarpyDefaultSkippedVersion];
[[NSUserDefaults standardUserDefaults] synchronize];
```
However, the check for whether a version was skipped within the method `showAlertIfCurrentAppStoreVersionNotSkipped:` only requires that the version string stored matches the `currentAppStoreVersion` string. Therefore, when `HarpyAlertTypeSkip` is used, user prompting will always be skipped after the initial prompt for the same App Store version regardless of user input.

Recommend removing the above lines as storage of `HarpyDefaultSkippedVersion` is also being performed within the `skipAlertAction` (as well as the UIAlertViewDelegate for iOS versions < 8.0) rendering the prior code redundant.

**Comment by ArtSabintsev** [comment]
Thanks for sending this through. I think I removed code recently that I thought was superfluous, but I may have been wrong. Will take a look at this in the evening and patch i tup.

Thanks, @nathanhosselton!

**Comment by ArtSabintsev** [comment]
ok just tested that suggestion - works perfectly. Thanks for being so diligent.

Will push a fix momentarily and add your name tot he contributions list.

**Comment by nathanhosselton** [comment]
You're welcome! And, thanks!
