### ISSUE TITLE
ios 6 compatible

### ISSUE THREAD

**Issue by levuhai** [ArtSabintsev/Harpy#72]
i got alot of error warning when running on Xcode 5.1.1 iOS 6.
Can you fix it?

**Comment by ArtSabintsev** [comment]
Please upgrade to XCode 6 and iOS 7. Not sur did you knew this, but Xcode 1-6, combined, have less than 4% market share.

**Comment by ArtSabintsev** [comment]
The reason it errors is due to APIs I use that are compatible with iOS 7 and beyond. 

Closing this issue as there's no need to support iOS 7 at this point in time.
