### ISSUE TITLE
Invisibles?

### ISSUE THREAD

**Issue by gurre** [ArtSabintsev/Harpy#73]
I've got some really strange errors when trying to import.

    Harpy/Harpy.m:39:21: Cannot find protocol declaration for 'UIAlertViewDelegate'
    Harpy/Harpy.m:387:4: Expected a type
    Harpy/Harpy.m:398:4: Expected a type
    Harpy/Harpy.m:411:4: Expected a type
    Harpy/Harpy.m:427:20: Expected a type
    Harpy/Harpy.m:78:21: Use of undeclared identifier '_presentingViewController'
    Harpy/Harpy.m:243:5: Use of undeclared identifier 'UIAlertView'
    Harpy/Harpy.m:243:18: Use of undeclared identifier 'alertView'
    Harpy/Harpy.m:244:5: Use of undeclared identifier 'UIAlertController'
    Harpy/Harpy.m:244:24: Use of undeclared identifier 'alertController'

I've tried the standard stuff. Reforked, cleaned project, restarted xcode, show invisibles, and delete and retryping some of the lines.

Any suggestions?

**Comment by gurre** [comment]
Important: UIAlertViewDelegate is deprecated in iOS 8. (Note that UIAlertView is also deprecated.) To create and manage alerts in iOS 8 and later, use UIAlertController.

**Comment by ArtSabintsev** [comment]
Hey @gurre,

Is this a manual installation or a CocoaPods installation?
Also, is your app's deployment target set to 8.1?

Also, I use both `UIAlertVIewDelegate` and `UIAlertController` in the library, to support people who target both iOS 8 and iOS 7.

**Comment by ArtSabintsev** [comment]
I'm assuming you've either fixed this issue, or moved on. Feel free to respond if the issue still persists.
