### ISSUE TITLE
Strong reference on presentingViewController

### ISSUE THREAD

**Issue by tflhyl** [ArtSabintsev/Harpy#78]
Is there any reason why it is strong reference?

**Comment by ArtSabintsev** [comment]
I'm using it because I want Harpy to own the reference to the `presentingViewController`. Also, I'm not trying to avoid retain cycles, so there's no need to use any other keywords.

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmPractical.html
