### ISSUE TITLE
How to add Arabic localisation in Bundle ? 

### ISSUE THREAD

**Issue by roman0914** [ArtSabintsev/Harpy#79]
Hi, thanks for great sdk for iOS.
I just noticed that your Harpy doesn't support Arabic language. So I am going to add it myself . But I couldn't find any way to add localisation strings for Arabic language. How can I proceed with this ? 

Thanks in advance.

**Comment by ArtSabintsev** [comment]
Hey @roman0914,

If you can, please translate these strings as accurately as you can, and I'll do the rest.
```
"A new version of %@ is available. Please update to version %@ now." 

"Update Available"

"Next time"

"Skip this version"

"Update"
```

**Comment by roman0914** [comment]
Thanks so much for reply.
I would send the translation tomorrow . 

Thanks again

**Comment by ArtSabintsev** [comment]
Hey, are you still interested in doing this translation?

**Comment by roman0914** [comment]
Hi thanks for messing me , I have been contacting my client to get Arabic translation . Please wait some more time .  Best .

**Comment by ArtSabintsev** [comment]
ok, sounds good. I'm closing this issue for now. Make a Pull Request once it's done. 

Thanks!
