### ISSUE TITLE
Feature: This app is no longer supported 

### ISSUE THREAD

**Issue by frranck** [ArtSabintsev/Harpy#84]
Hello,
I would like to be able to "terminate" an app by showing the user a  pop up saying "This app is no longer supported + please install xxx"
The user then would be redirected to a the second app. This would be triggered based on the version number of the second app.
Would you consider such a feature ?

**Comment by ArtSabintsev** [comment]
Hi @frranck,

Harpy comes with delegate methods that let you force that kind of update. 

https://github.com/ArtSabintsev/Harpy#optional-delegate-and-delegate-methods

Take a look at them!

**Comment by frranck** [comment]
thanks

**Comment by ArtSabintsev** [comment]
np - good luck!

**Comment by ArtSabintsev** [comment]
Also, https://github.com/ArtSabintsev/Siren, my Swift port, has better delegate methods that may be more useful, if you don't mind using both languages in your codebase.
