### ISSUE TITLE
Harpy (3.3.4) -- Harpy.h Error

### ISSUE THREAD

**Issue by romeocodemagnus** [ArtSabintsev/Harpy#85]
Error: Unknown type name 'UIViewController'
Property with 'retain or (strong)' attribute must be of object type
----------
/**
 The UIViewController that will present an instance of UIAlertController
 */
@property (strong, nonatomic) UIViewController *presentingViewController;

Error: Unknown type UIColor
Property with 'retain or (strong)' attribute must be of object type
-------------
/**
 @b OPTIONAL: The tintColor for the alertController
 */
@property (strong, nonatomic) UIColor *alertControllerTintColor;

**Comment by getaaron** [comment]
Looks like you're trying to use Harpy in a Mac (or other non-UIKit target).

**Comment by ArtSabintsev** [comment]
Thanks for responding, @getaaron! Closing this issue.
