### ISSUE TITLE
Arabic translation.

### ISSUE THREAD

**Issue by roman0914** [ArtSabintsev/Harpy#86]
Hello @ArtSabintsev , 

It has been a month since I asked you to make this library support Arabic. Sorry for the delay and here I send you arabic translation as requested.

____________________________

A new version of Almosafer is available. Please update to version 1.3 now.
تحديث جديد لتطبيق %@ ، حدث للنسخة الجديدة %@ الآن 

Update Available
نسخة جديدة 

Next time
لاحقاً

Skip this version
لا ، شكراً

Update
حدث الآن

____________________________
Regards
Romanov

**Comment by ArtSabintsev** [comment]
Thanks, @roman0914! I'll add this into this repo and to the Siren repo tomorrow morning.

**Comment by ArtSabintsev** [comment]
Actually, doing some google translate reverse translation shows that a lot of the translations are not really accurate.

**Comment by roman0914** [comment]
Can I help you something ? As I am familiar with RTL , I can help you put this translation into your SDK. Thanks.

**Comment by ArtSabintsev** [comment]
I think the translation is not accurate enough.

**Comment by roman0914** [comment]
تحديث جديد لتطبيق %@ ، حدث للنسخة الجديدة %@ الآن

Did you mean this translation is incorrect ? 
You may know first %@ is for version number , and second %@ is for app's name because Arabic just supports RTL . 

Thanks.

**Comment by ArtSabintsev** [comment]
Yes, the translation is incorrect - or so it seems to be from what I've gathered.

**Comment by roman0914** [comment]
could you please let me know what exactly is incorrect so that I can correct the translation  ?

**Comment by ArtSabintsev** [comment]
While I don't speak Arabic, the various translators I put the translations through state that the meaning of the messages isn't accurate enough. Extra or different words are used.

**Comment by roman0914** [comment]
It is correct. if you can use the translator of google , it will translate the first sentence like this 
"Reload new application @%, occurred the new version% @ Now" . 
At a glance, there is no issue with the transition as the meaning of all words are capable of using for Arabic translation .

**Comment by ArtSabintsev** [comment]
Correct, but I want it to be as close as possible to the original version I have written.

For instance, 'Reload new application' is not the same thing at all as "A new version of %@ Please update%@".

**Comment by roman0914** [comment]
I understand . But that is the sentence which is more user-friendly .

**Comment by ArtSabintsev** [comment]
Unfortunately, I disagree in this regard. I appreciate your effort, but I am looking for a more 1-to-1 translation for this project.

**Comment by ArtSabintsev** [comment]
@roman0914 I just pushed version 3.3.5 of Harpy and version 0.4.2 of Siren - both contain Arabic localization. Thanks for helping out!

**Comment by roman0914** [comment]
Thank you so much.  It really is a great news. I will download new version of Harpy.  What is Siren? Would you please give me short description of Siren? 

Regards.

**Comment by ArtSabintsev** [comment]
Siren is the Swift port of Harpy - http://github.com/artsabintsev/Siren

**Comment by roman0914** [comment]
Hello , I just tested the Harpy sdks but is not capable of showing Arabic localization. 

Please check Harpy.bundle and ar.lproj . You named it wrong “SirensLocalizable.strings” . So , it wasn’t able to load Arabic localisation exactly. It is a small thing but developers should update the name themselves. 

Hope it would be helpful . 

Thanks 
Romanov

**Comment by ArtSabintsev** [comment]
Whoops - will fix it now!

**Comment by ArtSabintsev** [comment]
ok - done! Thanks!
