### ISSUE TITLE
Override localization text

### ISSUE THREAD

**Issue by permagnus** [ArtSabintsev/Harpy#89]
Hi,

I want to override some texts in the current localization. How would I do that? I think that it would be great if you could specify a bundle to use for localization if you want to provide your own text messages.

**Comment by ArtSabintsev** [comment]
Hi @permagnus,

If you want to override the text yourself, fork the current repo, and then edit the text for the language of interest in `Harpy.bundle`: https://github.com/ArtSabintsev/Harpy/tree/master/Harpy/Harpy.bundle
