### ISSUE TITLE
Thai translation

### ISSUE THREAD

**Issue by kong707** [ArtSabintsev/Harpy#91]
Hi,
Can you add Thai Translation to Harpy ?

Here is the translated text
"A new version of %@ is available. Please update to version %@ now." = "เวอร์ชั่นใหม่ของ %@ สามารถใช้งานได้แล้ว กรุณาอัพเดทแอพให้เป็นเวอร์ชั่น %@ ";

/* Update alert title */
"Update Available" = "มีการอัพเดท";

/* Update alert dismiss button title */
"Next time" = "ไว้คราวหน้า";

/* Update alert skip button title */
"Skip this version" = "ข้ามเวอร์ชั่นนี้";

/* Update alert skip button title */
"Update" = "อัพเดท";

**Comment by ArtSabintsev** [comment]
Hey @kong707,

I'll add this in today/tonight to both this repository and Siren (http://github.com/ArtSabintsev/Siren)

**Comment by ArtSabintsev** [comment]
Added this to both Harpy and Siren. Will push to master on both repos in the next 15 minutes - just updating READMEs.
