### ISSUE TITLE
Suggestion: add harpyWillShowUpdateDialog before setting up the alert

### ISSUE THREAD

**Issue by yoavschwartz** [ArtSabintsev/Harpy#92]
I had a problem for example because checkVersion is async and by the time the request finished I was already in another view controller at which point I got the error "Attempting to show alert in non existent VC". In order to solve it I added a protocol method and a delegate call harpyWillShowUpdateDialog  to - (void)showAlertWithAppStoreVersion:(NSString *)currentAppStoreVersion right at the start before the VC for the alert is set, at which point I used the call to change the VC to present. I would make a pull request but it's really a 2 line-er so it's probably easier to change by hand if you like the idea.
P.S
Amazing plugin. useful,simple,well-made. Thank you.

**Comment by ArtSabintsev** [comment]
Thanks.

Siren,the Swift port of Harpy, has this feature in place. I haven't gotten a chance to port it to Harpy, but I will soon.

**Comment by yoavschwartz** [comment]
Thank you :) I also added support for implied 0 when patch version is missing, that is x.y.z so when z is missing so we have a common x.y versioning I turned it to x.y.0 . Otherwise the system right now, always goes for the default harpy alert even though different setting were set. I know it doesn't strictly follow the protocol, but it would make the framework highly useful for people who use 2 digit systems and not affect the people who do keep the protocol.

**Comment by ArtSabintsev** [comment]
Take a look at Siren. It has all those features :) 

http://github.com/artsabintsev/Siren

I have some time coming up in 2 weeks, where I hope to build Harpy up to speed with Siren.

**Comment by yoavschwartz** [comment]
Cool. I was a bit resistant to installing swift libraries into my project since iOS 7 support is still a requirement and I highly prefer not to manually handle the plugins I use, but I guess I'll make an exception this time. 

Yoav.

**Comment by ArtSabintsev** [comment]
I understand. I'll update this issue once I've made the necessary changes to ID.me. 

iOS 7 support should be dropped. According to Apple, it's at 14% adoption, globally. Just my 2 cents :)

**Comment by yoavschwartz** [comment]
If it was my decision we would only be supporting iOS 9 haha.

**Comment by ArtSabintsev** [comment]
Hah, I'm with you there. Closing this issue for now, as it's on my TO-DO list anyway.
