### ISSUE TITLE
Support minimumOsVersion [Feature request]

### ISSUE THREAD

**Issue by raven** [ArtSabintsev/Harpy#94]
Current implementation would alert iOS 7 users of new version even if the min target got bumped to iOS 8.
Would be nice if it checked minimumOsVersion.

**Comment by ArtSabintsev** [comment]
Hi Raven,

I had a solution for this in place using dynamic data (https://github.com/ArtSabintsev/Harpy#supported-devices-compatibility), but it stopped working as Apple stopped updating those keys on their end.

I'll consider revisiting this scenario using a custom, manually set value.

Thanks!
