### ISSUE TITLE
Wrong IF in method checkIfAppStoreVersionIsNewestVersion ?

### ISSUE THREAD

**Issue by brbgyn** [ArtSabintsev/Harpy#95]
Hi, i'm experiencing an awkward behavior in the method checkIfAppStoreVersionIsNewestVersion.

My app is in version 6.1 in the App Store, it has Harpy and i'm about to release version 6.2.

When the checkIfAppStoreVersionIsNewestVersion method runs, harpy correctly gets current version (6.2) and app store version (6.1).

But the IF in checkIfAppStoreVersionIsNewestVersion is never TRUE ! And the commands to show the alert are never fired. Trying "!=" instead of "==" works, but my online version 6.1 that is currently at the App Store has the "==" as the original Harpy.m file. Due to that i do not know if Harpy is going to work... What can you guys tell me about that ?

Follows code
```
- (void)checkIfAppStoreVersionIsNewestVersion:(NSString *)currentAppStoreVersion
{
    // Current installed version is the newest public version or newer (e.g., dev version)
    NSLog(@"%@",[self currentVersion]);
    NSLog(@"%@",currentAppStoreVersion);
    if ([[self currentVersion] compare:currentAppStoreVersion options:NSNumericSearch] == NSOrderedAscending) {
        NSLog(@"FIRED 1");
        [self localizeAlertStringsForCurrentAppStoreVersion:currentAppStoreVersion];
        [self alertTypeForVersion:currentAppStoreVersion];
        [self showAlertIfCurrentAppStoreVersionNotSkipped:currentAppStoreVersion];
    }else{
        NSLog(@"FIRED 2");
    }
}
```
Following is the log:
```
2015-07-27 12:29:51.023 Tesouro Direto[3103:607] 6.2
2015-07-27 12:29:51.023 Tesouro Direto[3103:607] 6.1
2015-07-27 12:29:51.024 Tesouro Direto[3103:607] FIRED 2
```

**Comment by ArtSabintsev** [comment]
Can you please provide me with a link to your app so i can obtain it's iTunes App Store ID?

Thanks!

**Comment by brbgyn** [comment]
Hi,

The ID is 859955280

https://itunes.apple.com/app/id859955280

**Comment by ArtSabintsev** [comment]
Thanks. I'll take a look in the next 24 hours.

**Comment by brbgyn** [comment]
Thank you

**Comment by brbgyn** [comment]
It's happening on both Device and Simulator, iOS 7 and 8.

**Comment by ArtSabintsev** [comment]
First week of a new job this week, so I'm bit busy. I will definitely get to this this week. It's in my calendar, so it will get done :+1:

**Comment by brbgyn** [comment]
No problem.
Good luck for u in ur new job :four_leaf_clover:

**Comment by ArtSabintsev** [comment]
Thanks.

So I'm not following your exact problem. It looks like everything is working as expected. Can you please elaborate on your problem once more? The more detail the better.

**Comment by getaaron** [comment]
@brbgyn The alert is only expected to appear when the App Store version is newer than the version being run. In your example, the App Store version is older, so the alert does not appear.

**Comment by brbgyn** [comment]
OMG. Thank you man...

Simple things can disturb us some times.

My mistake.

Thanks again

**Comment by brbgyn** [comment]
Thank you @getaaron

**Comment by Stunner** [comment]
@brbgyn please close this if your issue is resolved (or never was a real issue), helps newcomers assess the state of this library. :)
