### ISSUE TITLE
Don't dismiss alert if it's HarpyAlertTypeForce

### ISSUE THREAD

**Issue by cerupcat** [ArtSabintsev/Harpy#97]
Is there an option to not dismiss the alert if they click "update" when the alert type is HarpyAlertTypeForce?

**Comment by ArtSabintsev** [comment]
No, that's not possible to begin with. What you can do is follow the instructions in the code block for what you should do in the `- (void)applicationWillEnterForeground:(UIApplication *)application` method, if that's a situation you're trying to handle.
